// server/seedStores.js
import dotenv from "dotenv";
import { connectToDb, getDb } from "./db.js";

dotenv.config({ path: "../.env" });

const stores = [
  {
    name: "Fashion Nova",
    url: "https://www.fashionnova.com",
    description: "Modern Y2K and hip-hop styles.",
    decades: ["2000s"],
    styleTags: ["low-rise jeans", "crop tops", "bodycon dresses", "bling accessories"],
    isSmallBusiness: false,
    rating: 4.2,
  },
  {
    name: "PrettyLittleThing",
    url: "https://www.prettylittlething.us",
    description: "Trendy 2000s-inspired pieces.",
    decades: ["2000s"],
    styleTags: ["velour tracksuits", "mini skirts", "low-rise jeans", "corset tops"],
    isSmallBusiness: false,
    rating: 4.0,
  },
  {
    name: "Dolls Kill",
    url: "https://www.dollskill.com",
    description: "Edgy Y2K, rave, and alt fashion.",
    decades: ["2000s", "1990s"],
    styleTags: ["platform boots", "mesh tops", "rave wear", "low-rise jeans"],
    isSmallBusiness: false,
    rating: 4.5,
  },
  {
    name: "Depop",
    url: "https://www.depop.com",
    description: "Secondhand 90s and 2000s pieces from independent sellers.",
    decades: ["1990s", "2000s"],
    styleTags: ["vintage denim", "graphic tees", "cargo pants", "track jackets"],
    isSmallBusiness: true,
    rating: 4.8,
  },
  {
    name: "Poshmark",
    url: "https://www.poshmark.com",
    description: "Resale marketplace with lots of Y2K and 2000s pieces.",
    decades: ["2000s"],
    styleTags: ["velour tracksuits", "denim skirts", "low-rise jeans"],
    isSmallBusiness: true,
    rating: 4.1,
  },
  {
    name: "Free People",
    url: "https://www.freepeople.com",
    description: "Bohemian, 70s-inspired dresses and separates.",
    decades: ["1970s"],
    styleTags: ["bell-bottoms", "boho dresses", "peasant blouses", "fringe jackets"],
    isSmallBusiness: false,
    rating: 4.3,
  },
  {
    name: "Etsy Vintage 70s",
    url: "https://www.etsy.com",
    description: "Independent sellers offering authentic 70s vintage pieces.",
    decades: ["1970s"],
    styleTags: ["platform shoes", "disco shirts", "maxi dresses"],
    isSmallBusiness: true,
    rating: 4.7,
  },
  {
    name: "Lisa Says Gah",
    url: "https://lisasaysgah.com",
    description: "Indie boutique with 70s-inspired prints and silhouettes.",
    decades: ["1970s", "1990s"],
    styleTags: ["maxi dresses", "boho", "printed blouses"],
    rating: 4.7,
    isSmallBusiness: true,
  },
  {
    name: "House of Sunny",
    url: "https://www.houseofsunny.co.uk",
    description: "Bold retro knits and statement pieces with 70s and Y2K vibes.",
    decades: ["1970s", "2000s"],
    styleTags: ["maxi dresses", "babydoll tops", "color blocking"],
    rating: 4.5,
    isSmallBusiness: true,
  },
  {
    name: "UNIF",
    url: "https://www.unifclothing.com",
    description: "Alt and grunge-inspired pieces with 90s and 2000s edge.",
    decades: ["1990s", "2000s"],
    styleTags: ["baggy jeans", "graphic tees", "grunge"],
    rating: 4.4,
    isSmallBusiness: true,
  },
  {
    name: "Free People",
    url: "https://www.freepeople.com",
    description: "Boho and festival fashion with strong 70s influence.",
    decades: ["1970s", "1990s"],
    styleTags: ["peasant blouses", "maxi dresses", "boho"],
    rating: 4.3,
    isSmallBusiness: false,
  },
  {
    name: "Lazy Oaf",
    url: "https://www.lazyoaf.com",
    description: "Playful graphics and Y2K streetwear silhouettes.",
    decades: ["1990s", "2000s"],
    styleTags: ["babydoll tops", "graphic tees", "y2k"],
    rating: 4.2,
    isSmallBusiness: true,
  },
  {
    name: "Beyond Retro",
    url: "https://www.beyondretro.com",
    description: "Curated vintage from 70s, 80s, 90s and early 2000s.",
    decades: ["1970s", "1980s", "1990s", "2000s"],
    styleTags: [
      "bell-bottom pants",
      "power suits",
      "flannel shirts",
      "low-rise jeans",
    ],
    rating: 4.6,
    isSmallBusiness: false,
  },
  {
    name: "The Hippie Shake",
    url: "https://www.thehippieshake.co.uk",
    description: "Reworked 70s-inspired pieces with authentic prints.",
    decades: ["1970s"],
    styleTags: ["bell-bottom pants", "maxi dresses", "boho"],
    rating: 4.8,
    isSmallBusiness: true,
  },
  {
    name: "Stussy",
    url: "https://www.stussy.com",
    description: "90s and 2000s streetwear and skate style.",
    decades: ["1990s", "2000s"],
    styleTags: ["baggy jeans", "hoodies", "streetwear"],
    rating: 4.4,
    isSmallBusiness: false,
  },
  {
    name: "ASOS Marketplace",
    url: "https://marketplace.asos.com",
    description: "Curated vintage and indie 80s, 90s, and Y2K pieces from independent sellers.",
    decades: ["1980s", "1990s", "2000s"],
    styleTags: ["vintage denim", "band tees", "slip dresses", "track jackets"],
    isSmallBusiness: true,
    rating: 4.4,
  },
  {
    name: "Urban Outfitters",
    url: "https://www.urbanoutfitters.com",
    description: "Modern takes on 90s and 2000s streetwear and indie styles.",
    decades: ["1990s", "2000s"],
    styleTags: ["baggy jeans", "graphic tees", "mini dresses", "cargo pants"],
    isSmallBusiness: false,
    rating: 4.1,
  },
  {
    name: "Ragstock",
    url: "https://ragstock.com",
    description: "Affordable vintage and retro-inspired 70s–2000s clothing.",
    decades: ["1970s", "1980s", "1990s", "2000s"],
    styleTags: ["Hawaiian shirts", "mom jeans", "windbreakers", "band tees"],
    isSmallBusiness: false,
    rating: 4.3,
  },
  {
    name: "80sTees",
    url: "https://www.80stees.com",
    description: "Graphic tees and merch with heavy 80s and 90s nostalgia.",
    decades: ["1980s", "1990s"],
    styleTags: ["graphic tees", "movie merch", "cartoon prints"],
    isSmallBusiness: true,
    rating: 4.6,
  },
  {
    name: "ThredUp",
    url: "https://www.thredup.com",
    description: "Online thrift and consignment with plenty of 90s and Y2K pieces.",
    decades: ["1990s", "2000s"],
    styleTags: ["mom jeans", "baby tees", "slip dresses", "denim skirts"],
    isSmallBusiness: true,
    rating: 4.2,
  },
  {
    name: "Cider",
    url: "https://www.shopcider.com",
    description: "Trendy, social-media-ready 90s and Y2K-inspired fashion.",
    decades: ["1990s", "2000s"],
    styleTags: ["cargo skirts", "baby tees", "cropped cardigans", "low-rise pants"],
    isSmallBusiness: false,
    rating: 4.3,
  },
  {
    name: "Edikted",
    url: "https://edikted.com",
    description: "Bold Y2K clubwear and 90s street style.",
    decades: ["1990s", "2000s"],
    styleTags: ["cargo pants", "corset tops", "micro skirts", "graphic tanks"],
    isSmallBusiness: false,
    rating: 4.2,
  },
  {
    name: "Tunnel Vision",
    url: "https://shoptunnelvision.com",
    description: "Indie shop with true vintage and 70s/90s-inspired pieces.",
    decades: ["1970s", "1990s"],
    styleTags: ["flared pants", "band tees", "sheer tops", "boho prints"],
    isSmallBusiness: true,
    rating: 4.7,
  },
  {
    name: "Thrifted",
    url: "https://www.thrifted.com",
    description: "UK-based curated vintage with 80s, 90s, and Y2K focus.",
    decades: ["1980s", "1990s", "2000s"],
    styleTags: ["denim jackets", "track jackets", "oversized sweaters"],
    isSmallBusiness: true,
    rating: 4.5,
  },
  {
    name: "Lost Boys Vintage",
    url: "https://www.etsy.com/ca/shop/Lostboysvintage",
    description: "Etsy shop specializing in true 90s and Y2K graphic tops and denim.",
    decades: ["1990s", "2000s"],
    styleTags: ["graphic tees", "denim vests", "raver tees", "grunge tops"],
    isSmallBusiness: true,
    rating: 4.8,
  },
  {
    name: "Ian Drummond Vintage",
    url: "https://iandrummondvintage.com",
    description: "Vintage shop with pieces spanning 70s through early 2000s.",
    decades: ["1970s", "1980s", "1990s", "2000s"],
    styleTags: ["printed blouses", "knit tops", "maxi skirts", "tailored coats"],
    isSmallBusiness: true,
    rating: 4.6,
  },
  {
    name: "Gecko Hawaii",
    url: "https://geckohawaii.com",
    description: "Revived 80s and 90s surf and skate brand.",
    decades: ["1980s", "1990s"],
    styleTags: ["neon windbreakers", "graphic shorts", "beach shirts"],
    isSmallBusiness: true,
    rating: 4.4,
  },
  {
    name: "Juicy Couture",
    url: "https://juicycouture.com",
    description: "Iconic Y2K velour tracksuits and logo-heavy pieces.",
    decades: ["2000s"],
    styleTags: ["velour tracksuits", "logo hoodies", "bling accessories"],
    isSmallBusiness: false,
    rating: 4.3,
  },
  {
    name: "Demonia Cult",
    url: "https://demoniacult.com",
    description: "Alt footwear with 90s and 2000s goth, punk, and rave vibes.",
    decades: ["1990s", "2000s"],
    styleTags: ["platform boots", "chunky Mary Janes", "goth shoes"],
    isSmallBusiness: true,
    rating: 4.7,
  },
  {
    name: "Dripcrime",
    url: "https://dripcrime.com",
    description: "Streetwear and alt tees with Y2K aesthetic.",
    decades: ["1990s", "2000s"],
    styleTags: ["graphic tees", "oversized hoodies", "y2k prints"],
    isSmallBusiness: true,
    rating: 4.2,
  },
];

async function seed() {
  try {
    await connectToDb();
    const db = getDb();
    const collection = db.collection("stores");
    
    await collection.deleteMany({});
    await collection.insertMany(stores);
    
    console.log("✅ Seeded stores collection with", stores.length, "documents");
    process.exit(0);
  } catch (err) {
    console.error("Error seeding stores:", err);
    process.exit(1);
  }
}

seed();